/**
 * Ask RemAssist — knowledge base (single source of truth).
 *
 * Powers the live chat widget (components/widgets/AskRemAssist.tsx). Replaces the
 * thin 7-answer quick map with the rich, current library the site already answers:
 * all 12 service lines, commercials, delivery, company info, plus an out-of-scope
 * guard so "do you do X?" never lies about a trade we do not perform.
 *
 * RemAssist-Html/assets/ask-remassist.js is left untouched (static .dc.html target).
 */

/* ---- Contact / external constants --------------------------------------- */
export const CONTACT = {
  phone: '(832) 230-2194',
  tel: 'tel:+18322302194',
  email: 'support@remassistance.com',
  mailto: 'mailto:support@remassistance.com',
  book: 'https://calendly.com/j-zemene-remassistance/new-meeting',
  linkedin: 'https://www.linkedin.com/company/rem-assistance/',
  instagram: 'https://www.instagram.com/remassist',
  youtube: 'https://www.youtube.com/@RemAssistant',
  trustpilot: 'https://www.trustpilot.com/review/remassistance.com',
  /* The Google Business Profile by CID — the place itself, not the /maps/place/…
     URL a browser shows, which carries coordinates and a session token. */
  google: 'https://www.google.com/maps?cid=10709335694294039363',
};

/* ---- Link targets (current Next.js routes + external) ------------------- */
export const LIN: Record<string, string> = {
  pricing: '/pricing',
  qualify: '/qualify',
  how: '/how-it-works',
  faq: '/faq',
  reviews: '/reviews',
  cases: '/case-studies',
  privacy: '/privacy-policy',
  terms: '/terms-of-service',

  sales_revenue: '/services/sales-and-revenue',
  customer_service: '/services/customer-service-agents',
  finance: '/services/finance-and-accounting',
  backoffice: '/services/virtual-back-office-team',
  gtm: '/services/gtm-teams',
  sdr: '/services/sdr-as-a-service',
  managedit: '/services/managed-it',
  hr: '/services/hr-and-recruiting',
  industry: '/services/industry-specific',
  marketing: '/services/marketing-and-content',
  ai: '/services/ai-and-automation',
  extra: '/services',

  certs: '/#certifications',
  fit: '/#fit-finder',
};

export type KbLink = [label: string, href: string];
export type KbEntry = {
  id: string;
  kw: string[];
  title?: string;
  text?: string[];
  links?: KbLink[];
  chips?: string[]; // ids of other entries offered as follow-ups
};

/**
 * Trades visitors sometimes ask us to perform ourselves. Rem Assist is an
 * outsourcing partner, not a field-services company — so "do you have a home
 * cleaning service?" must not fall through to the generic services answer,
 * which reads as a yes. These get an explicit no, followed by the work we
 * really do run for companies in that trade.
 *
 * Phrases, never bare words: "cleaning" on its own would swallow "data
 * cleaning", which is genuine VA work.
 */
export const OUTSIDE: { label: string; kw: string[] }[] = [
  { label: 'cleaning',         kw: ['home cleaning', 'house cleaning', 'office cleaning', 'commercial cleaning', 'cleaning service', 'cleaning services', 'cleaning company', 'janitorial', 'housekeeping', 'maid service'] },
  { label: 'plumbing',         kw: ['plumbing', 'plumber'] },
  { label: 'electrical work',  kw: ['electrician', 'electrical service', 'electrical work'] },
  { label: 'HVAC',             kw: ['hvac', 'air conditioning', 'heating and cooling', 'furnace repair'] },
  { label: 'landscaping',      kw: ['landscaping', 'lawn care', 'lawn mowing', 'gardening service'] },
  { label: 'pest control',     kw: ['pest control', 'exterminator'] },
  { label: 'moving',           kw: ['moving company', 'movers', 'removals', 'relocation service'] },
  { label: 'construction',     kw: ['construction', 'handyman', 'carpentry', 'painting service', 'renovation'] },
  { label: 'catering',         kw: ['catering', 'caterer', 'food delivery', 'meal prep'] },
  { label: 'physical security',kw: ['security guard', 'security guards', 'guard service', 'patrol service'] },
  { label: 'auto repair',      kw: ['auto repair', 'car repair', 'mechanic', 'towing', 'body shop'] },
  { label: 'salon and spa work', kw: ['salon', 'barber', 'spa service', 'massage', 'nail tech'] },
  { label: 'childcare',        kw: ['childcare', 'child care', 'babysitting', 'daycare', 'nanny'] },
  { label: 'home care',        kw: ['home care', 'elder care', 'caregiver', 'nursing home'] },
  { label: 'laundry',          kw: ['laundry service', 'dry cleaning'] },
  { label: 'courier and delivery', kw: ['courier', 'truck driver', 'delivery driver', 'rideshare', 'taxi service'] },
  { label: 'pet care',         kw: ['pet grooming', 'dog walking', 'veterinary', 'pet sitting'] },
  { label: 'tutoring',         kw: ['tutoring', 'tutor'] },
  { label: 'photography',      kw: ['photography', 'videography', 'photographer'] },
];

/* ---- Knowledge base ------------------------------------------------------ */
/* prettier-ignore */
export const KB: KbEntry[] = [

  /* ---------- conversational ---------- */
  { id: 'greeting',
    kw: ['hi', 'hello', 'hey', 'hiya', 'yo', 'howdy', 'greetings', 'good morning', 'good afternoon', 'good evening', 'good day', 'hi there', 'anyone there', 'how are you', 'hope you are well'],
    title: 'Ask anything, in your own words',
    text: ['Teams, pricing, onboarding, security — answered instantly. Or tap a topic below.'],
    /* No links: the widget renders its own book / message / call row on the
       welcome card, so a KB link here would only duplicate it. Four chips —
       the card is the one screen every visitor sees, so it carries the full
       shortcut row while later replies stay capped at three. */
    chips: ['services', 'pricing', 'how_it_works', 'trial'] },

  { id: 'menu',
    kw: ['menu', 'options', 'topics', 'what can you do', 'what can you answer', 'what can i ask', 'help me', 'commands'],
    title: 'Here is what I can cover',
    text: ['• Services — 12 lines, from sales to HR to AI',
           '• Pricing — Pro from $8/hr, Expert from $11/hr',
           '• How it works, trial, onboarding',
           '• Security, quality, reviews'],
    links: [['Browse all services', LIN.extra], ['Pricing', LIN.pricing], ['Qualify in two minutes', LIN.qualify]],
    chips: ['services', 'pricing', 'how_it_works', 'book'] },

  { id: 'thanks',
    kw: ['thanks', 'thank you', 'thankyou', 'appreciate it', 'cheers', 'thx', 'much appreciated', 'awesome', 'perfect', 'brilliant'],
    text: ['Happy to help. If you want specifics for your own setup, the consultation is free and every engagement starts with a pilot before you commit.'],
    chips: ['trial', 'how_it_works', 'book'] },

  { id: 'bye',
    kw: ['bye', 'goodbye', 'good night', 'goodnight', 'see you', 'see ya', 'talk to you later', 'take care'],
    text: ['Thanks for stopping by — we are reachable 24/7 at ' + CONTACT.phone + ' or ' + CONTACT.email + ' whenever you are ready.'],
    links: [['Book a consultation', CONTACT.book]],
    chips: ['contact', 'book'] },

  { id: 'human',
    kw: ['human', 'real person', 'speak to someone', 'talk to someone', 'talk to a person', 'representative', 'sales rep', 'live agent', 'operator', 'are you a bot', 'you are a bot', 'are you human', 'are you real', 'are you a person', 'someone to call me'],
    title: 'Straight through to a person',
    text: ['I am an automated assistant — but I can hand you over to the team, who cover sales and support 24/7.',
           '• Phone — ' + CONTACT.phone,
           '• Email — ' + CONTACT.email,
           '• Or book a free consultation at a time that suits you'],
    links: [['Book a consultation', CONTACT.book], ['Call ' + CONTACT.phone, CONTACT.tel], ['Email us', CONTACT.mailto]],
    chips: ['contact', 'book'] },

  /* ---------- services overview ---------- */
  { id: 'services',
    kw: ['service', 'services', 'what do you do', 'what do you offer', 'offering', 'offerings', 'solutions', 'product', 'products', 'portfolio', 'capabilities', 'outsourcing', 'outsource', 'bpo', 'what you do'],
    title: 'A bench of trained seats, hired as teams',
    text: ['• Sales & Revenue — SDRs, list builders, cold callers, setters, email campaigns',
           '• Customer Service — voice, chat & email inside your helpdesk, 24/7',
           '• Finance & Accounting — bookkeeping, AP/AR, month-end close',
           '• HR & Recruiting — sourcing, screening, interview coordination',
           '• Marketing & Content — campaigns, SEO, social, brand',
           '• AI & Automation, Managed IT, Virtual Back Office, GTM pods, SDRs — and more.',
           'Every seat is a dedicated remote hire trained on your stack — never a shared pool.'],
    links: [['See all services', LIN.extra], ['Pricing', LIN.pricing], ['Fit finder', LIN.qualify]],
    chips: ['sales', 'customer_service', 'finance', 'gtm', 'pricing'] },
/* ---------- individual service lines ---------- */
  { id: 'sales',
    kw: ['sales and revenue', 'sales', 'revenue', 'sdr', 'sdrs', 'list building', 'list builder', 'cold call', 'cold calling', 'cold callers', 'appointment setter', 'appointment setting', 'email outreach', 'email campaign', 'pipeline', 'prospecting', 'lead generation', 'virtual sales'],
    title: 'Sales & Revenue',
    text: ['Six seats that build the list, work the channels, and put qualified meetings on your calendar — hired as one trained pod, without the recruiting cycle.',
           '• Outbound SDRs — list building, sequences, cold calls, booking',
           '• List builders and data researchers — ICP-matched accounts, verified',
           '• Appointment setters and email campaign managers',
           'You interview and approve every rep, and the trial is free.'],
    links: [['Learn more', LIN.sales_revenue], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['leadgen', 'sdr', 'gtm', 'pricing'] },

  { id: 'customer_service',
    kw: ['customer service', 'customer support', 'customer experience', 'customer care', 'support agent', 'support team', 'service agent', 'helpdesk agent', 'call center', 'call centre', 'contact center', 'contact centre', 'csat', 'front line', 'voice support', 'live chat', 'email support', 'after sales'],
    title: 'Customer Service',
    text: ['Dedicated agents answering your customers by voice, chat and email — inside your helpdesk, trained on your product, working your macros.',
           '• 24/7 coverage, any timezone',
           '• 100% of interactions QA-reviewed by a named supervisor',
           '• Under 60s average first response on live chat',
           'You approve every agent before they answer a single customer.'],
    links: [['Learn more', LIN.customer_service], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['voice', 'live_chat', 'email_support', 'pricing'] },

  { id: 'finance',
    kw: ['finance', 'accounting', 'bookkeeping', 'bookkeeper', 'bookkeepers', 'accounts payable', 'accounts receivable', 'ap ar', 'payroll', 'month end', 'month-end close', 'reconciliation', 'quickbooks', 'xero', 'financial'],
    title: 'Finance & Accounting',
    text: ['Bookkeeping, AP/AR, payroll, reconciliation and month-end close, run as one coordinated finance desk.',
           '• Month-end is a review, not an excavation',
           '• You keep the signature; we do the work behind it',
           '• Preparer and approver are different people, under audited ISO 27001 controls',
           'Pro seats from $8/hr, Expert from $11/hr — a 30–60 day pilot comes first.'],
    links: [['Learn more', LIN.finance], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['backoffice', 'security', 'pricing', 'trial'] },

  { id: 'backoffice',
    kw: ['back office', 'back-office', 'admin support', 'administrative', 'data entry', 'order processing', 'virtual assistant', 'operations associate', 'operations support', 'paperwork', 'inbox management', 'executive assistant'],
    title: 'Virtual Back Office Team',
    text: ['Product experts, software experts, account admins, bookkeepers, data-entry and order-processing clerks — the seats that keep operations running behind the front line.',
           '• Hired as one trained unit; you approve every agent before they start',
           '• Coverage can run 24/7 inside any helpdesk or ERP you already use',
           '• QA on every ticket, under ISO 9001 and ISO 27001 controls',
           'Seats from $8/hr (Pro) or $11/hr (Expert) — free trial on every engagement.'],
    links: [['Learn more', LIN.backoffice], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['virtual_assistant', 'finance', 'pricing', 'trial'] },
{ id: 'gtm',
    kw: ['gtm', 'go to market', 'go-to-market', 'gtm team', 'gtm pod', 'pod', 'marketing team', 'revops', 'rev ops', 'revenue operations', 'crm admin', 'marketing ops', 'growth team'],
    title: 'GTM Teams — a pod hired as one unit',
    text: ['Skip six hiring cycles. We assemble outbound, marketing ops and CRM administration into a single team that runs your motion end to end.',
           '• Seat 1 — GTM Lead: owns the plan and your weekly report',
           '• Seats 2–3 — SDRs: list building, sequencing, calls, booking',
           '• Seat 4 — Marketing VA: content, social, SEO support',
           '• Seat 5 — RevOps / CRM Admin: pipelines and automations in GHL or HubSpot',
           'Pods run 2–6 seats depending on your motion.'],
    links: [['Learn more', LIN.gtm], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['sdr', 'marketing', 'reporting', 'pricing'] },

  { id: 'sdr',
    kw: ['sdr', 'sdrs', 'sdr as a service', 'sales development', 'outbound', 'appointment setting', 'cold email', 'prospecting', 'book meetings', 'booked meetings', 'sequences', 'cadence', 'bdr', 'sales rep', 'closer'],
    title: 'SDR as a Service',
    text: ['Niche-trained SDRs who build lists, run multi-channel sequences and book qualified meetings — a full outbound engine without the hiring cycle.',
           '• List building — ICP-matched accounts, verified',
           '• Sequencing — email, phone and LinkedIn cadences in GHL or HubSpot',
           '• Qualification and booking — replies worked to a meeting on your AE’s calendar',
           'First sequences go live about two weeks from kickoff.'],
    links: [['Learn more', LIN.sdr], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['leadgen', 'sales', 'gtm', 'pricing'] },

  { id: 'managedit',
    kw: ['managed it', 'it help desk', 'it helpdesk', 'helpdesk', 'help desk', 'it support', 'managed service', 'sysadmin', 'system admin', 'network support', 'tech support', 'infrastructure', 'devops', 'it team', 'endpoint', 'cybersecurity', 'co-managed', 'cloud infrastructure', 'cyber security'],
    title: 'Managed IT',
    text: ['Endpoints, help desk, security, and cloud — run as one coordinated layer, under the same ISO 9001 and ISO 27001-aligned controls as the rest of Rem Assist.',
           '• Managed IT Services — endpoints, networks and monitoring',
           '• IT Help Desk — Tier 1 and Tier 2 support',
           '• Cybersecurity & Compliance — threat monitoring and access control',
           '• Cloud & Infrastructure — Microsoft 365/Google Workspace, backup and recovery',
           'Available Co-Managed (alongside your IT team) or Fully Managed.'],
    links: [['Learn more', LIN.managedit], ['Book a consultation', CONTACT.book]],
    chips: ['ai_automation', 'security', 'pricing'] },

  { id: 'hr',
    kw: ['hr', 'recruiting', 'recruitment', 'hr and recruiting', 'sourcing', 'screening', 'interview coordination', 'onboarding administration', 'resume screening', 'candidate', 'candidates', 'applicant', 'talent', 'ats', 'hris', 'hiring'],
    title: 'HR & Recruiting',
    text: ['Sourcing, screening, interview coordination and onboarding administration, run inside your ATS and HRIS by a seat you interview.',
           '• Recruiting operations — sourcing, resume screening, pipeline, coordination',
           '• Every applicant read against your written scorecard, with reasoning shown',
           '• HR administration — onboarding, paperwork, accounts, day-one readiness',
           'Every hiring decision still lands with you.'],
    links: [['Learn more', LIN.hr], ['Book a consultation', CONTACT.book]],
    chips: ['backoffice', 'industry', 'pricing'] },
{ id: 'industry',
    kw: ['industry specific', 'industry', 'industries', 'sector', 'niche', 'saas', 'ecommerce', 'e-commerce', 'healthcare', 'fintech', 'real estate', 'insurance', 'legal', 'roofing', 'logistics', 'do you work with', 'vertical'],
    title: 'Industries we staff',
    text: ['Our generalist bench adapts to any helpdesk or product within days. For accounts that need it, we place agents from dedicated niche tracks — SaaS support, e-commerce, healthcare admin, fintech — who arrive already speaking your customers’ language.',
           'If your sector is not on that list, it is almost certainly still a fit.'],
    links: [['Learn more', LIN.industry], ['Book a consultation', CONTACT.book]],
    chips: ['customer_service', 'backoffice', 'reviews', 'book'] },

  { id: 'marketing',
    kw: ['marketing', 'marketing and content', 'seo', 'social media', 'content marketing', 'campaign', 'email marketing', 'advertising', 'ppc', 'newsletter', 'funnel', 'brand', 'content', 'branding', 'copywriting', 'blog'],
    title: 'Marketing & Content',
    text: ['Strategic marketing services including SEO, social media, campaigns and funnel builds inside GoHighLevel or HubSpot.',
           '• Marketing support — campaign assembly, email/social scheduling, SEO',
           '• Content & brand — one voice across every channel, held to a written guide',
           '• Research & analysis — market, competitor and ICP sweeps',
           'On a GTM pod this runs as the marketing seat; standalone it runs as its own seat or project.'],
    links: [['Learn more', LIN.marketing], ['GTM Teams', LIN.gtm], ['See pricing', LIN.pricing]],
    chips: ['content_brand', 'gtm', 'pricing'] },

  { id: 'ai_automation',
    kw: ['ai', 'ai and automation', 'artificial intelligence', 'automation', 'automate', 'workflow automation', 'zapier', 'make.com', 'n8n', 'rpa', 'ai agent', 'ai receptionist', 'chatgpt', 'llm', 'automations'],
    title: 'AI & Automation',
    text: ['AI plus human assistance for the administrative duties that never stop — cold calling, billing, CRM, data entry and more.',
           '• AI Automations — build in Zapier, Make.com and n8n, with a human on every exception',
           '• AI Implementation — from business formation to AI-integrated operations',
           '• Four controls, and you hold all four: supervisor, exceptions, logs, kill-switch',
           'Nothing fails silently, and nothing you approve runs without your sign-off.'],
    links: [['Learn more', LIN.ai], ['Book a consultation', CONTACT.book]],
    chips: ['it_helpdesk', 'backoffice', 'security', 'pricing'] },

  { id: 'extra_services',
    kw: ['extra service', 'extra services', 'other service', 'other services', 'additional service', 'more services', 'what else', 'a la carte', 'full bench', 'all services'],
    title: 'Extra Services — the rest of the bench',
    text: ['The same bench covers the rest of a company’s operations. Take a single role or a whole pod.',
           '• Sales & Revenue, Customer Service, Finance & Accounting',
           '• Back Office, Managed IT, HR & Recruiting',
           '• Industry-Specific staff, Marketing & Content, AI & Automation',
           'Most clients buy a seat, not a service — one trained seat often covers several of these.'],
    links: [['See all services', LIN.extra], ['Pricing', LIN.pricing]],
    chips: ['it_helpdesk', 'backoffice', 'marketing', 'pricing'] },
/* ---------- commercials ---------- */
  { id: 'pricing',
    kw: ['price', 'prices', 'pricing', 'cost', 'costs', 'rate', 'rates', 'how much', 'quote', 'budget', 'fee', 'fees', 'hourly', 'per hour', 'expensive', 'cheap', 'affordable', 'package', 'plan', 'plans', 'per hour rate'],
    title: 'Pricing, in short',
    text: ['Two published rates — nothing hidden, no discovery call required to learn them.',
           '• Pro — from $8 per hour per seat',
           '• Expert — from $11 per hour per seat',
           'Everything past that is customized in the consultation.',
           'Every engagement starts with a free pilot, and you can see the full monthly grid on the pricing page.'],
    links: [['See all plans', LIN.pricing], ['Qualify in two minutes', LIN.qualify], ['Book a consultation', CONTACT.book]],
    chips: ['tiers', 'trial', 'contract', 'billing'] },

  { id: 'tiers',
    kw: ['pro vs expert', 'tier', 'tiers', 'seniority', 'expert agent', 'pro agent', 'experience level', 'junior', 'senior', 'level of experience', 'skill level', 'quality of agents'],
    title: 'Two tiers, one bench',
    text: ['• Pro — from $8/hr. Fully trained and fit for work from day one. Clears our core program and picks up any software you run.',
           '• Expert — from $11/hr. More years on the job and a far more rigorous assessment path. Arrives fluent in your motion and needs the least direction.',
           'You can mix tiers inside one pod — an Expert lead over Pro seats is the most common and the cheapest way to buy senior judgment.',
           'Either tier operates under ISO 9001 quality management and ISO 27001 information security.'],
    links: [['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['pricing', 'training', 'quality'] },

  { id: 'trial',
    kw: ['free trial', 'trial', 'pilot', 'pilot program', 'try before', 'test it', 'risk free', 'proof of concept', 'poc', 'sample', 'demo period', 'trial period', 'free pilot'],
    title: 'Pilot program, not a blind commitment',
    text: ['We do not run traditional free trials — the training and security setup is too involved. Instead there is a 30–60-day pilot: a dedicated team at smaller scale, so you can measure our SLAs and quality firsthand before a full rollout.',
           'The consultation itself is always free.'],
    links: [['See pricing', LIN.pricing], ['How it works', LIN.how], ['Book a consultation', CONTACT.book]],
    chips: ['how_it_works', 'contract', 'pricing'] },

  { id: 'contract',
    kw: ['contract', 'commitment', 'cancel', 'cancellation', 'notice period', 'change plan', 'switch plan', 'scale up', 'scale down', 'add seats', 'remove seats', 'minimum term', 'lock in', 'long term', 'flexible'],
    title: 'Terms stay flexible',
    text: ['You can add or remove plans at any time, and scale seats up or down as demand moves — our reps handle the transition so coverage never drops.',
           'All terms stay negotiable through the consultation, including payment structures aligned to your revenue cycle.'],
    links: [['Read the FAQ', LIN.faq], ['Book a consultation', CONTACT.book]],
    chips: ['billing', 'trial', 'pricing'] },

  { id: 'billing',
    kw: ['invoice', 'invoicing', 'billing', 'payment', 'pay', 'payment terms', 'upfront', 'deposit', 'currency', 'monthly bill', 'how do i pay'],
    title: 'Billing and payment',
    text: ['Pricing is per hour per seat, and payment structures are aligned with your revenue cycles rather than a fixed template. There are no upfront fees on the hiring side — you only pay once you hire.',
           'The exact schedule, currency and invoicing cadence get set in the consultation.'],
    links: [['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['contract', 'trial', 'pricing'] },
/* ---------- delivery ---------- */
  { id: 'how_it_works',
    kw: ['how it works', 'how does it work', 'process', 'onboarding', 'get started', 'getting started', 'timeline', 'how long', 'how fast', 'steps', 'next step', 'ramp', 'setup', 'start date', 'lead time'],
    title: 'From consult to coverage in four steps',
    text: ['• Day 0 — Free consultation: the services you need and your expected volume. Always free.',
           '• Day 1–2 — Team design: we scope the personnel mix, pricing and terms.',
           '• Day 3 — Pick your agents: review profiles and interview, or leave selection to us.',
           '• Day 4–14 — Monitored training and delivery: full training, work logs, daily reports, and a free trial.',
           'Most clients go from first call to a fully onboarded pod inside two weeks.'],
    links: [['See the full process', LIN.how], ['Book a consultation', CONTACT.book]],
    chips: ['training', 'trial', 'reporting', 'pricing'] },

  { id: 'hiring_roles',
    kw: ['what roles', 'which roles', 'roles', 'position', 'positions', 'job title', 'hire', 'hiring', 'staffing', 'recruit', 'candidate', 'candidates', 'interview', 'profiles', 'choose agents', 'replace agent', 'roles you can fill'],
    title: 'Roles you can fill',
    text: ['We place executive assistants, bookkeepers and AP/AR, operations associates, customer support, SDRs, sales reps, data entry, reporting, and marketing assistants — among others.',
           'You review vetted candidate profiles and can interview them. If none feel like a fit, you pay nothing — we keep looking or part ways.'],
    links: [['Read the FAQ', LIN.faq], ['Book a consultation', CONTACT.book]],
    chips: ['how_it_works', 'tiers', 'pricing'] },

  { id: 'training',
    kw: ['training', 'train', 'trained', 'training process', 'how do you train', 'onboard agents', 'product training', 'sop', 'documentation', 'learning curve', 'ramp up', 'shadow'],
    title: 'Training, before the first ticket',
    text: ['Agents complete rigorous assessments before placement, then a collaborative training process on your systems — your macros, your tone-of-voice guide, your SLAs — before they touch live work.',
           'If nothing is documented yet, we build the SOP during onboarding and hand it back to you. You keep it whether or not you stay.'],
    links: [['Learn more', LIN.customer_service], ['Book a consultation', CONTACT.book]],
    chips: ['how_it_works', 'quality', 'pricing'] },

  { id: 'reporting',
    kw: ['report', 'reports', 'reporting', 'monitoring', 'work log', 'work logs', 'time tracking', 'time tracker', 'screenshot', 'productivity', 'transparency', 'daily report', 'kpi', 'dashboard', 'oversight'],
    title: 'What lands in your inbox',
    text: ['AI-assisted monitoring with hourly work logs and daily email reports on every seat. GTM pods add a weekly pipeline report and a standup with your pod lead.',
           'The time-tracking client is available on request only — it is never required.'],
    links: [['GTM Teams', LIN.gtm], ['Book a consultation', CONTACT.book]],
    chips: ['quality', 'gtm', 'how_it_works'] },

  { id: 'quality',
    kw: ['quality', 'iso 9001', 'qa', 'quality assurance', 'scoring', 'performance', 'guarantee', 'accountability', 'standards', 'audit', 'csat'],
    title: 'Quality is measured, not promised',
    text: ['Rem Assist holds ISO 9001:2015 for quality management. On customer service accounts, 100% of interactions are QA-reviewed against a 95%+ CSAT target; on outbound, we report meetings held rather than activity counts.',
           'KPIs are set together at the start, then reported against every week.'],
    links: [['Verify our certifications', LIN.certs], ['Read reviews', CONTACT.trustpilot],
            ['Book a consultation', CONTACT.book]],
    chips: ['security', 'reporting', 'reviews'] },

  { id: 'security',
    kw: ['security', 'iso 27001', 'data protection', 'gdpr', 'compliance', 'nda', 'confidential', 'hipaa', 'pci', 'secure', 'data safe', 'privacy of data', 'infosec', 'breach', 'vulnerability'],
    title: 'Security and certification',
    text: ['Rem Assist is certified to ISO 9001 (quality) and ISO/IEC 27001 (information security), audited by a third party.',
           'Access is least-privilege and scoped per client, with named risk owners and a live risk register.',
           'None of your data trains anything, and NDAs and compliance terms are settled before work starts.'],
    links: [['Learn more', LIN.certs], ['Privacy Policy', LIN.privacy], ['Book a consultation', CONTACT.book]],
    chips: ['quality', 'privacy', 'contact'] },

  { id: 'hours',
    kw: ['hours', 'coverage', 'timezone', 'time zones', 'timezones', 'after hours', 'after-hours', 'extended hours', '24/7', 'nights', 'weekends', 'overnight'],
    title: 'Coverage and hours',
    text: ['Coverage is flexible — part-time seats are real, and you do not have to buy 160 hours to start.',
           '• Anything past 40 hours a week means more than one person, which is exactly what a pod is for.',
           '• True 24/7 means a pod of three to six across timezones, covering nights and weekends without overtime.',
           'Tell us the hours you need and we will shape seats around them.'],
    links: [['Book a consultation', CONTACT.book]],
    chips: ['customer_service', 'backoffice', 'pricing'] },

  { id: 'languages',
    kw: ['language', 'languages', 'english', 'bilingual', 'multilingual', 'spanish', 'french', 'arabic', 'accent', 'native speaker'],
    title: 'Languages',
    text: ['Our agents work in English by default, across voice, chat and email. For any other language requirement, tell us the market on the call and we will confirm what we can staff before you commit.'],
    links: [['Book a consultation', CONTACT.book]],
    chips: ['contact', 'locations', 'how_it_works'] },
/* ---------- extra services, itemised ---------- */
  { id: 'it_helpdesk',
    kw: ['it help desk', 'it helpdesk', 'helpdesk', 'help desk', 'it support', 'sysadmin', 'system admin', 'network support', 'endpoint', 'co-managed'],
    title: 'Managed IT',
    text: ['Endpoints, help desk, security, and cloud — run as one coordinated layer under ISO-aligned controls.',
           '• Managed IT Services — endpoints, networks and monitoring',
           '• IT Help Desk — Tier 1 and Tier 2 support',
           '• Cybersecurity & Compliance — threat monitoring and access control',
           '• Cloud & Infrastructure — Microsoft 365/Google Workspace, backup and recovery'],
    links: [['Learn more', LIN.managedit], ['Book a consultation', CONTACT.book]],
    chips: ['ai_automation', 'security', 'pricing'] },

  { id: 'virtual_sales',
    kw: ['virtual sales', 'sales team', 'sales rep', 'salesperson', 'closer', 'account executive', 'full cycle sales', 'inside sales', 'close deals'],
    title: 'Virtual Sales Teams',
    text: ['Full-cycle remote sales reps — beyond SDR work, through close — built to match your culture. Pair them with SDRs if you want the top of the funnel fed as well.'],
    links: [['Sales & Revenue', LIN.sales_revenue], ['SDR as a Service', LIN.sdr], ['Book a consultation', CONTACT.book]],
    chips: ['sdr', 'leadgen', 'pricing'] },

  { id: 'leadgen',
    kw: ['leadgen', 'lead gen', 'lead generation', 'leads', 'list building', 'data scraping', 'scraping', 'prospect data', 'contact data', 'enrichment', 'icp', 'data services'],
    title: 'Lead Generation & Data',
    text: ['AI data scraping plus lead gen and management tooling keeps your pipeline sourced and clean — accounts from LinkedIn Sales Navigator and Apollo, verified for accuracy before a single touch goes out.'],
    links: [['Sales & Revenue', LIN.sales_revenue], ['SDR as a Service', LIN.sdr], ['Book a consultation', CONTACT.book]],
    chips: ['sdr', 'sales', 'pricing'] },

  { id: 'research',
    kw: ['research', 'analysis', 'market research', 'competitor analysis', 'data analysis', 'analyst', 'insights', 'survey', 'pricing study'],
    title: 'Research & Analysis',
    text: ['Extensive research and analysis from our agents to enhance your product or service — market and competitor sweeps, pricing studies, and the recurring data pulls nobody has time for.'],
    links: [['All Services', LIN.extra], ['Book a consultation', CONTACT.book]],
    chips: ['leadgen', 'marketing', 'pricing'] },

  { id: 'content_brand',
    kw: ['content', 'content creation', 'copywriting', 'copywriter', 'brand management', 'branding', 'blog', 'social content', 'reputation management', 'video editing', 'graphic design', 'design support'],
    title: 'Content & Brand Management',
    text: ['Create and manage your online content across platforms, and build an identity that differentiates your company — including reputation and review management on the channels your buyers actually check.'],
    links: [['Marketing & Content', LIN.marketing], ['Book a consultation', CONTACT.book]],
    chips: ['marketing', 'pricing'] },

  { id: 'custom_software',
    kw: ['custom software', 'software development', 'app development', 'developer', 'developers', 'build an app', 'website', 'web development', 'api', 'integration', 'crm build', 'booking app'],
    title: 'Custom Software',
    text: ['We create and customize software that fits your specialty and industry — CRM, booking apps, AI analytics, sales funnels, email marketing, call tracking, document signing and more.',
           'We integrate with the systems you already run; none of it is mandatory, and if you prefer your own stack we work in yours.'],
    links: [['AI & Automation', LIN.ai], ['Book a consultation', CONTACT.book]],
    chips: ['ai_automation', 'it_helpdesk', 'pricing'] },

  { id: 'ai_implementation',
    kw: ['ai implementation', 'ai integration', 'ai consulting', 'ai strategy', 'ai adoption', 'implement ai', 'ai roadmap', 'llm'],
    title: 'AI Implementation',
    text: ['Implementation agents guide you from business formation to AI-integrated operations, with ongoing recommendations as the landscape changes — so the stack you adopt this quarter still makes sense next year.'],
    links: [['AI & Automation', LIN.ai], ['Book a consultation', CONTACT.book]],
    chips: ['ai_automation', 'custom_software', 'pricing'] },

  { id: 'virtual_assistant',
    kw: ['virtual assistant', 'virtual assistance', 'va', 'vas', 'assistant', 'executive assistant', 'personal assistant', 'remote assistant', 'remote staff', 'remote hire', 'dedicated assistant'],
    title: 'Virtual assistants, trained for the tools you run',
    text: ['Every Rem Assist VA clears a core program before placement and picks up whatever software you use — CRM, helpdesk, billing, scheduling, or the tool you built in-house.',
           'One seat can cover several jobs at once: inbox and calendar, order processing, CRM hygiene, reporting, research, or first-line customer contact.',
           'Pro seats start at $8/hour; Expert seats — more years, a harder path — start at $11/hour.'],
    links: [['Virtual Back Office', LIN.backoffice], ['See pricing', LIN.pricing], ['Book a consultation', CONTACT.book]],
    chips: ['backoffice', 'tiers', 'how_it_works', 'trial'] },
{ id: 'voice',
    kw: ['voice', 'voice support', 'phone support', 'inbound call', 'answering service', 'call answering', 'telephone', 'after hours', 'take calls', 'answer calls', 'voice channel', 'ivr'],
    title: 'Voice support',
    text: ['Inbound lines answered in your name, with call notes logged straight into your CRM. Overflow and after-hours options are included, so peaks and evenings never go unanswered.'],
    links: [['Learn more', LIN.customer_service], ['Book a consultation', CONTACT.book]],
    chips: ['live_chat', 'email_support', 'hours', 'pricing'] },

  { id: 'live_chat',
    kw: ['live chat', 'web chat', 'chat support', 'chat agent', 'messaging support', 'social dm', 'instant chat', 'customer chat'],
    title: 'Live chat',
    text: ['Real agents on live chat inside your helpdesk — under whatever branding and macros you already use, with a sub-60s average first response and QA on every interaction.'],
    links: [['Learn more', LIN.customer_service], ['Book a consultation', CONTACT.book]],
    chips: ['voice', 'email_support', 'pricing'] },

  { id: 'email_support',
    kw: ['email support', 'ticketing', 'ticket', 'tickets', 'queue', 'triage', 'zendesk', 'intercom', 'freshdesk', 'inbox management', 'sla', 'escalation'],
    title: 'Email and ticketing',
    text: ['Full queue ownership in Zendesk, Intercom, GoHighLevel — or whatever you run. Triage, resolution, tagging and escalation SOPs sit with the agent, not with your managers.'],
    links: [['Learn more', LIN.customer_service], ['Book a consultation', CONTACT.book]],
    chips: ['voice', 'live_chat', 'quality', 'pricing'] },

  { id: 'book',
    kw: ['book', 'booking', 'consultation', 'consult', 'schedule', 'appointment', 'meeting', 'demo', 'calendly', 'set up a call', 'speak to sales', 'free consultation', 'call with ', 'talk to the team'],
    title: 'Book a free consultation',
    text: ['Tell us the services you need and your expected volume, and we will come back with the seat mix, timeline and pricing. It is free, there is no commitment, and a pilot comes before anything is signed.'],
    links: [['Pick a time', CONTACT.book], ['See pricing first', LIN.pricing]],
    chips: ['how_it_works', 'trial', 'contact'] },
{ id: 'contact',
    kw: ['contact', 'contact you', 'phone number', 'your number', 'email address', 'reach you', 'get in touch', 'address', 'call you', 'support line', 'talk to sales', 'phone', 'email', 'reach'],
    title: 'How to reach us',
    text: ['• Phone — ' + CONTACT.phone,
           '• Email — ' + CONTACT.email,
           '• Book a free consultation at a time that suits you',
           'Support and sales are available 24/7.'],
    links: [['Call ' + CONTACT.phone, CONTACT.tel], ['Email us', CONTACT.mailto], ['Book a consultation', CONTACT.book]],
    chips: ['book', 'social', 'reviews'] },

  { id: 'locations',
    kw: ['where', 'location', 'locations', 'where are agents', 'based', 'office', 'offices', 'headquarters', 'address', 'country', 'countries', 'remote'],
    title: 'Where agents are based',
    text: ['Our teams work remotely from dedicated staffed offices. The delivery model is built to match your hours and timezone, and the exact footprint is confirmed on the consultation call.'],
    links: [['Book a consultation', CONTACT.book]],
    chips: ['contact', 'languages', 'how_it_works'] },

  { id: 'reviews',
    kw: ['review', 'reviews', 'testimonial', 'testimonials', 'trustpilot', 'google', 'google reviews', 'reference', 'references', 'case study', 'case studies', 'client', 'clients', 'proof', 'rating', 'reputation'],
    title: 'What clients say',
    text: ['We are rated 5.0 out of 5 on both Trustpilot and Google, across the four reviews currently live — you can read them verbatim on either profile, or side by side on the Reviews page.'],
    links: [['Reviews', LIN.reviews], ['Read them on Trustpilot', CONTACT.trustpilot], ['Read them on Google', CONTACT.google], ['Book a consultation', CONTACT.book]],
    chips: ['quality', 'about', 'book'] },

  { id: 'about',
    kw: ['about', 'about you', 'who are you', 'company', 'rem assist', 'remassistance', 'your team', 'founder', 'ceo', 'leadership', 'history', 'what does rem mean', 'rem stand for', 'remote standard'],
    title: 'About Rem Assist',
    text: ['Rem Assist builds remote teams that match your culture. The name is the standard: Results-driven, Efficient, Matching your culture, On target, Thoroughly excellent, Every time.',
           'The company is led by Johnathan Zemene (CEO) and Minassie Sora (COO).'],
    links: [['Follow on LinkedIn', CONTACT.linkedin], ['Read our reviews', CONTACT.trustpilot]],
    chips: ['services', 'locations', 'contact'] },
{ id: 'social',
    kw: ['linkedin', 'instagram', 'insta', 'youtube', 'facebook', 'tiktok', 'twitter', 'socials', 'social profiles', 'your social media', 'follow you', 'follow us', 'where can i find you'],
    title: 'Where to find us',
    text: ['• LinkedIn — company updates and hiring news',
           '• Instagram — team posts and behind the scenes',
           '• YouTube — service explainers and walkthroughs',
           'For anything you need answered directly, phone and email are the fastest.'],
    links: [['LinkedIn', CONTACT.linkedin], ['Instagram', CONTACT.instagram], ['YouTube', CONTACT.youtube]],
    chips: ['contact', 'about', 'reviews'] },

  { id: 'privacy',
    kw: ['privacy', 'privacy policy', 'terms', 'terms of service', 'policy', 'tos', 'data policy', 'sms consent', 'unsubscribe', 'opt out', 'cookies', 'legal'],
    title: 'Privacy and terms',
    text: ['Our Privacy Policy covers what we collect and how it is used; the Terms of Service cover the commercial relationship. Messaging consent is never a condition of purchase, and you can reply STOP to unsubscribe at any time.'],
    links: [['Privacy Policy', LIN.privacy], ['Terms of Service', LIN.terms]],
    chips: ['security', 'contact'] },

  { id: 'lead_capture',
    kw: ['quote', 'proposal', 'estimate', 'form', 'submit', 'reach out', 'get a quote', 'ask a question', 'send a message', 'leave a message', 'enquiry', 'inquiry'],
    title: 'Leave a message for the team',
    /* The widget has no in-chat form, so this must hand over a real channel
       rather than promise one. */
    text: ['Tell us who you are and what you need and it goes straight to the team. There is no commitment and no sales script, just a real answer.'],
    links: [['Email the team', CONTACT.mailto], ['Book a consultation', CONTACT.book]],
    chips: ['contact', 'book'] },

];

/**
 * Short labels for the follow-up chips. An entry's `title` is a full headline
 * ("A bench of trained seats, hired as teams") — far too long for a pill, so
 * the chip strip reads from here instead. Anything missing falls back to the
 * title, then the id.
 */
export const CHIP_LABEL: Record<string, string> = {
  greeting: 'Start over',
  menu: 'What can you answer?',
  human: 'Talk to a person',
  services: 'Your services',
  sales: 'Sales & revenue',
  customer_service: 'Customer service',
  finance: 'Finance',
  backoffice: 'Back office',
  gtm: 'GTM teams',
  sdr: 'SDR service',
  managedit: 'Managed IT',
  hr: 'HR & recruiting',
  industry: 'Industries',
  marketing: 'Marketing',
  ai_automation: 'AI & automation',
  extra_services: 'Extra services',
  pricing: 'Pricing',
  tiers: 'Tiers',
  trial: 'Free trial',
  contract: 'Contract terms',
  billing: 'Billing',
  how_it_works: 'How it works',
  hiring_roles: 'Roles you can fill',
  training: 'Training',
  reporting: 'Reporting',
  quality: 'Quality & QA',
  security: 'Security',
  hours: '24/7 coverage',
  languages: 'Languages',
  it_helpdesk: 'IT helpdesk',
  virtual_sales: 'Virtual sales',
  leadgen: 'Lead data',
  research: 'Research',
  content_brand: 'Content & brand',
  custom_software: 'Custom software',
  ai_implementation: 'AI implementation',
  virtual_assistant: 'Virtual assistants',
  voice: 'Voice support',
  live_chat: 'Live chat',
  email_support: 'Email & tickets',
  book: 'Book a consultation',
  contact: 'Contact details',
  locations: 'Where agents are',
  reviews: 'Reviews',
  about: 'About us',
  social: 'Follow us',
  privacy: 'Privacy & terms',
  lead_capture: 'Leave a message',
};

/** The label a chip shows for a given entry. */
export function chipLabel(e: KbEntry): string {
  return CHIP_LABEL[e.id] || e.title || e.id;
}